version: '2'
services:
  nextcloud:
    image: nextcloud
    volumes:
      - nextcloudStore:/var/www/html
      - squeegeeApp:/var/www/html/apps2/squeegee
      - ./config/apps.config.php:/var/www/html/config/apps.config.php
    ports:
      - "16000:80"
    environment:
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=database
      - NEXTCLOUD_TRUSTED_DOMAINS=*.*.*.*
      - SMTP_HOST=maildev
      - SMTP_PORT=25
      - SMTP_AUTHTYPE=NONE
      - MAIL_FROM_ADDRESS=test
      - MAIL_DOMAIN=test.com
    depends_on:
      - database
    links:
      - maildev:maildev
  database:
    image: mariadb
    restart: always
    volumes:
      - databaseStore:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  maildev:
    image: djfarrelly/maildev
    ports:
      - "7078:80"
      - "7025:25"
volumes:
  nextcloudStore:
  databaseStore:
  squeegeeApp:
    driver_opts:
      type: none
      device: ${PWD}/.
      o: bind