---
version: '3'
# This instance is using SQLite3 as database backend.
# Please consider using a proper database like MariaDB or PostgreSQL
# if you want to use this productive.

services:
  nextcloud:
    image: wonderfall/nextcloud:18
    depends_on:
      - nextcloud-db
    environment:
      - UID=1000
      - GID=1000
      - ADMIN_USER=mrrobot
      - ADMIN_PASSWORD=supercomplicatedpassword
      - SQUEEGEE_PROJECTS_ROOT=/projects/root
      - SQUEEGEE_CONNECTOR_URL=https://en71o1pwzzy02.x.pipedream.net
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=supersecretpassword
      - DB_HOST=nextcloud-db
    volumes:
      - nextcloudStore:/data
      - ./:/apps2/squeegee/
    ports:
      - 8888:8888
  nextcloud-db:
    image: mariadb
    volumes:
      - nextcloudDB:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecretpassword
volumes:
  nextcloudStore:
  nextcloudDB: